.PHONY: all build test proto lint run-server run-server-mock run-server-gemini android android-install clean

all: build

# Protobuf types are generated by the core crate's build script; nothing to do.
proto:
	@echo "protos are compiled during 'build' (core/build.rs)"

build:
	cargo build --workspace

test:
	cargo test --workspace

lint:
	cargo clippy --workspace --all-targets -- -D warnings

run-server:
	cargo run -p lares-server

# No API key or network required.
run-server-mock:
	LARES_ENGINE=mock cargo run -p lares-server

# Requires GEMINI_API_KEY.
run-server-gemini:
	LARES_ENGINE=gemini cargo run -p lares-server

android:
	./gradlew -p android assembleDebug

android-install:
	adb install -r android/app/build/outputs/apk/debug/app-debug.apk

clean:
	cargo clean