.PHONY: all build test proto lint run-server run-server-mock run-server-gemini android android-install clean

JAVA_HOME ?= /home/randozart/brief-tools/jdk-17.0.20+8
ANDROID_NDK_ROOT ?= /home/randozart/Android/Sdk/ndk/android-ndk-r27c

all: build

# Protobuf types are generated by the core crate's build script; nothing to do.
proto:
	@echo "protos are compiled during 'build' (core/build.rs)"

build:
	cargo build --workspace

test:
	cargo test --workspace

lint:
	cargo clippy --workspace --all-targets -- -D warnings

run-server:
	cargo run -p lares-server

# No API key or network required.
run-server-mock:
	LARES_ENGINE=mock cargo run -p lares-server

# Requires GEMINI_API_KEY.
run-server-gemini:
	LARES_ENGINE=gemini cargo run -p lares-server

android:
	JAVA_HOME="$(JAVA_HOME)" PATH="$(JAVA_HOME)/bin:$$PATH" ANDROID_NDK_ROOT="$(ANDROID_NDK_ROOT)" ./android/gradlew -p android assembleDebug

# Rebuild the APK and restart the server so /apk serves the newest build.
apk-update: android
	systemctl --user restart lares-server
	@echo "APK served at http://100.111.244.0:8787/apk"

android-install:
	adb install -r android/app/build/outputs/apk/debug/app-debug.apk

clean:
	cargo clean